
convert2indices = function(str){
	tmp = strsplit(str,"")[[1]]
	sapply(tmp,switch,"A"=1,"C"=2,"G"=3,"T"=4)
}

indices2dna = function(inds){
	sapply(inds,switch,"1"="A","2"="C","3"="G","4"="T")
} # indices2dna(c(1,2,3,4)) -> "A" "C" "G" "T"


kdict <- function(dna,ksize){
	nout = nchar(dna)-ksize+1
	nvec = character(nout)
	for(ii in seq( nout ))
		nvec[ii] <-substring(dna,ii,ii+ksize-1)
	nvec
}

tokenize = function(xx){
	strsplit(xx,"")[[1]]
}

getprofile <- function(mm,add=1){
	apply(mm,2,function(x) (table(factor(x,levels=c("A","C","G","T")))+add) / (length(x)+ (add*length(x)) )  )
}


bestmotif <- function(inds,profile,k){

	maxprob = -1
	maxmer = indices2dna(inds[1:k])
	nout = length(inds)-k+1
	for(ii in seq( nout )){
		slice = ii:(ii+k-1)
		tmpinds = inds[slice]
		thisprob = prod(profile[cbind(tmpinds,1:ksize)])
		if(thisprob > maxprob){
			#maxmer = substring(test,slice[1],tail(slice,1))
			maxmer = indices2dna(tmpinds)
			maxprob = thisprob
		}
	}
	maxmer
}


randmotif <- function(inds,profile,k)
{
	nout = length(inds)-k+1
	allprobs = numeric(nout)
	for(ii in seq( nout )){
		slice = ii:(ii+k-1)
		tmpinds = inds[slice]
		allprobs[ii] = prod(profile[cbind(tmpinds,1:ksize)])
	}
	ii = sample(seq(nout),1,prob=allprobs)
	slice = ii:(ii+k-1)
	indices2dna(inds[slice])
}

getscore <- function(mm){
	sum(apply(mm,2,function(x) { 
		tmptab = table(x)
		#major = names(tmptab)[which.max(tmptab)] # consensus base
		sum(tmptab) - tmptab[which.max(tmptab)]
	}))
}

# ksize = 8
# test = c("CGCCCCTCTCGGGGGTGTTCAGTAAACGGCCA",
# "GGGCGAGGTATGTGTAAGTGCCAAGGTGCCAG",
# "TAGTACCGAGACCGAAAGAAGTATACAGGCGT",
# "TAGATCAAGTTTCAGGTGCACGTCGGTGAACC",
# "AATCCACCAGCTCCACGTGCAATGTTGGCCTA")

# ksize = 8
# test = c("CGCCCCTCTCGGGGGTGTTCAGTAAACGGCCA",
# "GGGCGAGGTATGTGTAAGTGCCAAGGTGCCAG",
# "TAGTACCGAGACCGAAAGAAGTATACAGGCGT",
# "TAGATCAAGTTTCAGGTGCACGTCGGTGAACC",
# "AATCCACCAGCTCCACGTGCAATGTTGGCCTA")

ksize = 15
test = c("GGAAAATTTGTAGATCACTTACGCGTTTAGCGCAAGTTTTGTTTTACTGTTATTCTAGCTCGTGAGTGGGAACAGATACATATAGGATTCTAAGCAGCACTCACGTGCCGTGTCTGCTTCCCCGCCATGGATGCCAGCCTAGGCCGCTACGTGCATTGGCCAAAACACGCACTGAATGATTAATTGAGCCTATCGGGGGCAAGACCGCATGGAGTTCGCTCCAGAAAACTACGCATTAACGTACCGTCATTCGAACATCCAACCGTGTGGCAGTGATGGGCCGCTTGTGCAAATACTTTCCATCCGTGACGGAAAGATGGGAAAATTTGTAGAT",
"CACTTACGCGTTTAGCGCAAGTTTTGTTTTACTGTTATTCTAGCTCGTGAGTGGGAACAGATACATATAGGATTCTAAGCAGCACTCACGTGCCGTGTCTGCTTCCCCGCCATGGATGCCAGCCTAGGCCGCTACGTGCATTGGCCAAAACACGCACTGAATGATTAATTGAGCCTATCGGGGGCAAGACCGCATGGAGTTCGCTCCAGAAAACTACGCATTAACGTACCGTCATTCGAACATCCAACCGTGTGGCAGTACTGAATGCTGAGCAGATGGGCCGCTTGTGCAAATACTTTCCATCCGTGACGGAAAGATGGGAAAATTTGTAGAT",
"CTAGCCTTTTTTCATGCCTGAATATGCCCCTCCATCCACCAACCATATGGCTAGGCATGGTAGATCTCTTACGATTTATTGGCTGACTCCACCCGGCGCCCCCCGCGATCAGCCCGTGCGCCGTTACGCCAAATCTTCATACATAGACCTTCGGTAACAAAGTTCTTCTAATTTGGTTACCGCTCTTCAAATCGCCCAAGCCATCAGTGTTAGTCTGATCTGGCGGATTAAATGGAAACTACCGGCTGTACAGTGGAATTGCAGCTGCTGAGCAGAGTCGGCACATGACGGAATACCTGTCGAAACCCTTAATTCGGAAAGTATTCTCATACTT",
"ATTAATCGTATGCATAGCGGACAATAGGTTCTGGGCGTGCTTGCCGCGGTCCTCTAACACGCCCCTCTGCAGTATGGAACAAGTATTCCTAAGAACAGCGGCACGTGTTATAAGAAACCCCAACGAGTAACACCCCCGACCCGAGTAGCCTTACGGGGAGCGAGGATCCCGGCTTTCATCGTAGCAGGATTAATGTCGGGGGCGGGGATCCGCAGCCGATTCCAAGTGCCAGACTAGTACCTGAGCAAGATTGCCGTAATATGTCGTACAGAAAGTAGTCCGCCCTACTTTTCATTGTCACAGACACTACGGCCAGTAAGTTCTGCACCATCAC",
"AGGCAATACACGTGCGTGATGTAGTAGGATCGCTCAAGCCCCACATGGAATCTTTTGAATGATACCCGGCAGCATTCCCCCGCGAAAAAATTATGTATGGACTGGCCTTTGGGGCGTAGCCTTTCTAATTACTTCGTGCTACCGGTACCAGGTCATAGAAGGGCAACCGTATTTCTACTGCTTGGCAATTATAGTCAGCGGCTAAGTTACTAGCCAGTGAGCATTCATCGTATCTTTCCGGAAAGCAACGCGCACTAGGTTGGGGCCGGCCTACTTGTTCCACTGCCGCTACTGCTAAGCCGACGCGACACTATGGAGTTGCACCTGGAGGCTA",
"AGTAGAGTAATCCTTTAAACGGGGCACGCGGTTGGAACGTCATCTCACCTTCCGCGGTTGAGACCGCCGCCAGGTAGGATTTGGGGCCCGTTAGCTGCTGAGCTGGCGCAGGAGCTCAAATCTACACACTCCCTGTACCGACCATTTCGCTGCTCATTGCCCATATGGGCTCTCTTCATGACGGACTCTAGTGGGCAGAAAGTTAGCGTGTCCAGCCGAATTGTTTCTGGCATCCTTCGGATCTCCGCAAGACTAGTGCTGGGTCCGACCATGTCGGCTGATTGTCAATATACGGATCACCACTCTAGAGATCGATGATTTCGCGCGCCGGTTA",
"TACATCTGAGCCGGCGCTGGCTGGCCATCCACTGCCCTCACTGATTACTGCTCGATTAAGTTCTTCAGACACCGTGGGTAGTAGACGATTAAATACTCAAGGAACTCCTCTCGACCGCCGTTCCTTTTATAGAGGCTCGGGAGTTACTGGGGCTTGACGCAAGTGAGACTCGCTCACCGCCAAACTAGTGACTGAGCAGATCTCAGGTTGCGGTTTGAACTGGACATATTCACAACGTGTGGGGAAGATTAACATGGATCTGATTGACACCACCGACTGGCGAATTTCGCTCCATATTCAGTCGTAGGCACCCCGCAGAGTCAATACGCAATTG",
"CACGTCCCAAGCGGTGTATACGAGGGCACGACTAACGCCCGGTTAATCTCGCTTTAGCAACTAGCTCGCGAGCAAATTGAATCCTACGTTGCTCTTCGTTACCATGAATCGTGTATGGGTGTTAGGATCGACTGCCAGATTCCGCTGTTGGGCGGGCAGAAGGGACAAGATTGGTTGAGAGGTTCTGTGCCTCACTAACTGCCTTCCATGTTGTACTTTCTCTGAGCATGGCGTGCATGCTGGGAGGTATGTTTGTTCAAACTGCCTCGGCGACCTACTGTGCTTTAAGCCACATGCAGTTTTGATTCCTTAACGACTTCGCCTTCACGGTGAA",
"CCTTGTCGCGTGGTAGGTCGAGGCCGGTAAGACCTAGTTACGTTTTAGAGTGTAGGCTGCGTTGGACAAGTATCTAGCCGGCCGCGACCTAAATAACTAGTTAATACTAGCTGCTGGTGACTCGCATTTGAGCTGATGGTGATGGCTCCCGACACCTTAGTCACGAAAGGATGGCAAGCCAGTGCCTGCCACTCCGTCTCATTCATGTTTTTTTAAGAGAGTTGGTTTCCATTAAGCGTTTCACTAGTGTCGTGGGCGGATGATCCAGGGCCAATGGTGCCCTTTCTCCAGCGGAACTTTGTGCCGCACACGCGATGACGAGAAGAGGTTGCTT",
"CGTTACACCGAGAAAGGAATCTGACAATTCTTGGATTGTACTAGCAATTGAGCACGGCTGCATGGAAAAATAAACGCATGGGTCAGGTCTTGTGTCTAACGCACCTCCCAGCGCTTTGACCTGGCCATATTGTCACAAGTGGCGAAACTTCAGAATCAATTTAACCGGATAGGTATCTACTGTGATCTGACTCCCGGACGTGGGTACATGCGTCCAGGTTGCAGGTGCGGACCGGTACCGGAAGGGCCGCAATACAAGCTTTTTCTGGAACAGAAAACTCAGGTTCATCGCCGCACAAAGGGGCTTATCCACAATCCCCTTACTCCCGATCGAC",
"AGGTTCGACACAGTACACGTGAGGTGATTTAGACCGACTCGCCAGGCTAGCTGCTGAGGGCGACTATTCCCCGGTAAGCGATACGAGGAGCCCGAGCGCGTCTATCCAAGGTTCACGTAAATTCCTAGTAACGCGGCTTCGCCCTGGACTCCAGAGCGTGAAGTAAGTGATTCGCTCGCCTTGTCCCCTAAAAGTACAAATGCGCACGCTAATCGTGGATCCAAGTTAGTCACGCTTGCGTGTTCTCTGGTGAGTCAGATCACATACCCCTGTACGGATCCCGGGTTAGTCGTGCCGGTTACTCGGCACAGCACCCGAACCATGCTCATCGGGA",
"TGTACCCGGCCCAGTATGGCAGGAGGTAATCACCAACAACTGTGATAACAATCTTTCACCTCTTGCACATGTGTAAGCCCCGAGTGTAATAAAGAGTGCCCGTACGCCGACATTGTAGCCGCTCAATGGATCGTGGAGTCGACCAAGCACGTCTGTTCGGTTATTAATACTATTGGCTGAGCACCAGGGTAAGCACCCTGCATAATAATGAGATCGGAGCTAGGCGGCCGAGCCACGGCCAGGGTTCTTTGCTGTAGACTCGGTGCTTTCAGCGCGCTATGACCGACCCATTTCAACCCGCTGGAACCCCATCTTGTGAATGCATATTTTCCAG",
"AAACGTTTCTGGAATTGTCGGTTCCCGACACTGCCCACTGCTATTTAGCTCCGTCTATAACCAGTGCGCTGCCCTAACTTAGGACTACTGACGATGTAAACCTGACAGCGCCATCAACCCTCCAACAGTTCACTGCGCAGGGAAGGGATTGCAAGGAACAGAAATCCGGCAAGGGCCTTCGCCAGCGGCCTCAAGCTCGAAGACCTGTAATGATATTCTGTCAAGACGTGGAGTACTTTAACGCTGGTGACTGTTTGCTGAGCAGGCAACTTAAGCGTTGTCGCTCTTTGCCCTTTTTAAGTGCGTGGCCAACATCCAGGATTTTCGCCTATTA",
"ACACGCACGGCGGAAATCGCCCAATCCGACAGCACTAAGAGCAGCCCAATATTTCTTTTACCAATCGCATAGCGTGCTCCTATTTAGTCACCCTCACTAGCTGTCAAGCAACGGTTAGTCCATCTTACCCCATCTGATTAGCTACCTAAAAATAGGGGTTTTACGCTGAAACGAACGAATCTGCCGATAAGGCGATATTGTGGTAATCCTACGATTTGACTCGTTGGGCACTCTGGAATCGGGATCTTAACGCTAAGCATCGCTCAGCCAGTCCGTATTCAGTATCAAAATTACGGGAGCGGCCGGTTGGAATATTTCCTGCGCCGGGTGTGGA",
"GTTGCGGGAAATCAAATCCGATAATCACTTACCGACCGCGGTGACAAGTTCTCCTTCTCGCAAGAGGAAATAGGACATCGACTCGGAATAGTGGTGGTTCGCCGCTGGTTCGCCGGACTTTTTATCCAAGCCTGGGCCCGTGTAAGCCTGACCAATGGCGAGATATCAAGGCGCACTACAAGCTGAGCATAAGAAGCCATTGGAAGCTGCGTACTTTGATAGGCAGCAGGGCACCCTCGGCATCCGTCGCGGGCCGTCACGAAGAGGTCTCGAGTATAGGTAGAATCAGAGAAATGTGCGGTTGGCAAGCTCTGTTGCTGAGAACTACTAGACA",
"TGTTGCAACTTTGACTTCCTTTTACAGGACAGCTTTACATCTGGCGTGACCCCGTTAAGAACTGCCGGGGTATAGTTCGTCCCGTATTTGTGGCTCTAAAATATGGAGCCGCTGCTGAGCATAACTTTCGACGCATTGACAAAGCTAGTGTCTTCTGGCGACGACCCCTACGAAGTCGCATTCGTTCCTAATCGACCCACGAAGGCCTGCCACCATAAGCGTATGGCATAGAAAACCTCGCAGGCCCCAATATCTCAGCGGCTTGGGCGGAGGAAATGGGGCCAAGATGGTTTAAAAAAGATTGGAATAAAGATCTCGGGCCTTGTAACTCGGA",
"CTTAGCAGCTTTGTTTCCCAAGTCCTTCCCACTAGCTGCTCCACAACACACACCACATAACCTTCCTTCTTAACAACGCAATAGGGACCCCACAGGTAAGAATATTGGGTCTAACCTGATTCACCCATCAACGACAGTTTATATCAGAACCGGATTTCACCGGCACTTTACCATTCACGCCTGTTTGTAGTCTGGAATGGGGGTTATTATTGCCTGAGTGTGTCGGACGCGCCCTGCGAGACAGCTGAACTGGTGCCGTCAGATTGCACTCTCAACGGTATTTGAGAACGCGATAATCCTACGCAAGGGAGGGGACCCCCGACAGATCAACAAT",
"ATATCAAAAGCATTGTTCACTGAGGGATATGGTAACTGAACAGACGCTGTAACCTCGTCTACGGCTGATCAAGGCAGGTACTAGTCCACACGCTTGCGTCTGGCGAGCCTCGTTTGTCGATTAGATACTAGCTGCACCGCAGAGATTGGTTGACGCCTAGCTTATCATCATTTGATAAGTGCGCCGGCTATACTATACACTGGAGTACACTCGTGGTATCCTCCTTGGGTGTCGGCAGTAATGGCATCGGGTATTGTCCAGTCCTATTCCGTTTCTAAGTGTCCTCAACTGGGCAAACCGCCCAGCAACGAGTAACCTACCTTTATATATCCGG",
"GGAACTAGTTAAGTAGTCAGACTTTAAGACCTGGTCATTACGTGGCCAAACTGTATGTGGGGCTATCGTCCAGGCGAGATACCTACGCCCTCGTAGGGTCAGATATGGGGGAGGAGTGCGTTGTCATCAAACGTCCGCTCCTGCGTTTGGCTTAAGACACGCAAATTCTTCTAGACGTTCTATCACCCGACTTCTCCTCGAGGCTTTGCCCGCTGTAAGGAAACTGATTGCGATCACACGTTATCCGTAACGCGATCAACGAGTCACACCCCCTTGACTTGTTGACTCCTACATATTAACGTACTGCTGAGCAGTCCTAAAGTCATTCGTGCGC",
"GAAATACGCTCAGCATCGGCCAGCATGCAGATAGTACGGGAAACGTCGATGCGGTTAAGCGCTGGAGTTGTGGGAGATAGACGGTTATCACAGCAATGTATCGGACCTCTTGACCCCACACCGGTTGGCATCACAAGGTAATAGCGGAGGCGAGGTATTTGCATTCTACTTTAGGTATGATAGTATGACAAAGTTTGGATTCCATTGCTCAAAGGACCCAATTCTAGTCGTCTTGTTAGTACTCTCTATATCTTGCACCGTGCTGTAGAGTACCTCTATATCTGTACATAGCGGTAAGTCCGAGGAGCGTTCTCCATCACTAGCTGCTGAAATT")

indices = sapply(test,convert2indices)
superN = 10
supermax = Inf
superset = NA
regularN = 500
regularM = length(test)
for( sup in seq(superN))
{
	if(sup %% 10 == 0) cat(sprintf("%d%%...",(sup/superN)*100))
	klist = unname(sapply(test,kdict,ksize=ksize, simplify=FALSE))
	motifs = t(sapply(sapply(klist,sample,1),tokenize))
	maxscore = getscore(motifs)
	thisscore = 0
	maxset = motifs
	tsize = length(test)

	for(xxx in 1:regularN)
	{
		i = sample(seq(regularM),1)
		prof = getprofile(motifs[-i,])
		motifs[i,] <- randmotif(indices[,i],prof,ksize)
		#motifs = t(unname(apply(indices,2,bestmotif,profile=prof,k=ksize)))
		thisscore = getscore(motifs)
		if(thisscore < maxscore){
			maxscore = thisscore 
			maxset = motifs
		} else {
			#break
		}
	}

	if( maxscore < supermax){
		print(maxscore)
		supermax = maxscore
		superset = maxset
	}
}
cat("finished!\n")
supermax
cat(sprintf("%s\n",apply(superset,1,paste,collapse="")))



