
convert2indices = function(str){
	tmp = strsplit(str,"")[[1]]
	sapply(tmp,switch,"A"=1,"C"=2,"G"=3,"T"=4)
}

indices2dna = function(inds){
	sapply(inds,switch,"1"="A","2"="C","3"="G","4"="T")
} # indices2dna(c(1,2,3,4)) -> "A" "C" "G" "T"


kdict <- function(dna,ksize){
	nout = nchar(dna)-ksize+1
	nvec = character(nout)
	for(ii in seq( nout ))
		nvec[ii] <-substring(dna,ii,ii+ksize-1)
	nvec
}

tokenize = function(xx){
	strsplit(xx,"")[[1]]
}

getprofile <- function(mm,add=1){
	apply(mm,2,function(x) (table(factor(x,levels=c("A","C","G","T")))+add) / (length(x)+ (add*length(x)) )  )
}


bestmotif <- function(inds,profile,k){

	maxprob = -1
	maxmer = indices2dna(inds[1:k])
	nout = length(inds)-k+1
	for(ii in seq( nout )){
		slice = ii:(ii+k-1)
		tmpinds = inds[slice]
		thisprob = prod(profile[cbind(tmpinds,1:ksize)])
		if(thisprob > maxprob){
			#maxmer = substring(test,slice[1],tail(slice,1))
			maxmer = indices2dna(tmpinds)
			maxprob = thisprob
		}
	}
	maxmer
}

getscore <- function(mm){
	sum(apply(mm,2,function(x) { 
		tmptab = table(x)
		#major = names(tmptab)[which.max(tmptab)] # consensus base
		sum(tmptab) - tmptab[which.max(tmptab)]
	}))
}

# ksize = 8
# test = c("CGCCCCTCTCGGGGGTGTTCAGTAAACGGCCA",
# "GGGCGAGGTATGTGTAAGTGCCAAGGTGCCAG",
# "TAGTACCGAGACCGAAAGAAGTATACAGGCGT",
# "TAGATCAAGTTTCAGGTGCACGTCGGTGAACC",
# "AATCCACCAGCTCCACGTGCAATGTTGGCCTA")

ksize = 15
test = c("GCACACCGTTTCAGGAGTAATCTTGCGGATTCCGGGCTTCCGATATTAGAGATGCACATGCGTGGTCGGCACGTGTCATGCCTCTACCATCGGCGACGAAGACTTATTCTAAACAGGCTGTTGTTACGAGGTCAGATATGTCTCCTAGGCTGCATTCATAACCGCCACTGGCAGTAGGGTTCCGGATCCCTACGGTGCACACCGTTTCAGG",
"AGTAATCTTGCGGATTCCGGGCTTCCGATATTAGAGATGCACATGCGTGGTCGGCACCACCTAGATTGGAATGTGTCATGCCTCTACCATCGGCGACGAAGACTTATTCTAAACAGGCTGTTGTTACGAGGTCAGATATGTCTCCTAGGCTGCATTCATAACCGCCACTGGCAGTAGGGTTCCGGATCCCTACGGTGCACACCGTTTCAGG",
"CAGCGTCGAGTTTTCTCCTCAGGATCCCGTTGGTTAGCGGCGAATAACTGCGTCCCACGTTATCTGGTGTAAATCAACGGAGGGCCCCTAACGGCCCTCCGCCTAGCAGGAATGCGACTTACCCCGAAAGTCATTCCTTTGTCAATCCCTTACACGCGGCCAGGAATGATGAATTCCCTAATCCGTTGCCCCCAATTCCTCTCATCGATCC",
"CGTTTCAGAATAGATCGCATACAATTCGGGTACGGCGGGAGACTGGCAGTAGTGCATGTCAGGATTGCCTAGGGGAATCGAGATTGTGTACACGGTACAATAGTTTCCCATCTCAACCACTGCCATCAAGCACGCCACGTGATGAGCGGATTGGAATTTGTCAGCTGACGAATTTCAATTCGTGTCGTACTGGCTCCGCTCGGTTAATACC",
"AAAGCCAAACGACCCAACTTACGACGCGGGCATGCACTCGTAGTTTTAGACCGCGGGCGGTGCATCGTCTCGAATTGGGCGCACAGCTTGGGGGCCGCACAGTTAAACTAACACCTGAGGCAAGTAACACGCGTCGTGGAATTAAAGATCTCTGAGATACCTGAATGGAGAGCGAGGTAGTGTGTTGGGGCTCGGTCGAACCAATCGTTGC",
"GCCGCAGACTTCTTGCTGGGAGCTACGCAACAGAAAGGTAGGAACTATACCCCCCTTCAGACCGTCTAATGGCAAACCACATGGTAAATTCGCTCTCTTCTCTGAGTACAGTGAGCCGGACCGGGTCTACTCCGGCCACAACTTCCTTTAGACCCCCTAGTCATCCTGTTCCGTCTCCACTGAACCAGAACACGACTATTGGAATGCTTAC",
"GCTATGGCCTCCGAGGTATAGTTGTGTCTTTGGCGAGCCAAAACGTATCCGGATACTGAGGGGCGTGGGCAAACTAACAATTTGAGCATACCGTAAACTCTTAACACGCGGATAATAATGCGGAATGTGTATTCTAGTATTTTCCACAGCCATGAAGCCCTATTAGCGCGCTAAGAAAACTAGTAGTGGTAGCTCACATGCGCTGGCAGCC",
"GCCCAACGATTCGTATTAACATTGAGCCCGGTTCGAACTGGTCATATTGGACACAATTAAACTAGGCTGTGCAGCTGGACACGCACTGTCGTTGCCGAGAGGCTCGTTAGGTGCGTTTTGCGGACGATGACGGGTGACGTAGGGCACGACAATTGGAATCAGCTTCACAACCTTTCCATTACCGTGCATAATCATCCAGATGTCCTCCGAC",
"CTGTAATTTAATTTCTTATCATTAATGAGCAGCGGCTCTAACTATGCAAGTCACGCGATCTGGAATCTGTAGGTCTATGCTTAAAGTTAGACCCGGAGAGTAATACTACTCACGTTTTTGAGGGATCCAGCAGGGAACTGCAGTTGGTGAGGCGCTCCGATGGACAGGGCCCCAAAATGTATGTTTGCAAGCAGAGATATACTTCGGCTTA",
"AACTCGCGACCTTATAGTCCATGAATACTCCAGAAGGTTATTTGCGCTAACCACAGAGACAAGGTCTGCTGGTTAACAGTTGGATTGGAATAAGTCTCGTGCGTATATAGTTCACCTCAAAACAGGTCGACCTATGCGGAAGATACGAAGGCCATGTTCCCACTTTAAGGCTTATCATAAAGAAAGAGTTTGCTCCTTTGCAACCGCTGGT",
"TCAGCCGTCGATCGTCCGACCTTGTCAGTTAAGACCGGTGCCACTAAAGAGCAATTTCCTGGCGAAGTGAATCGGAACTGATCGCCTGTTTGACCTTTAAGATATGCCACGCGGATTCTGATTAGGTTTCTTTCCCTAGGCGGCTCCTGCAGCAATAGCTAAACTAAGTATCCCGCGGCTTGAAGTTGGTGTGCAAAGCATGATAAAGGGA",
"CCCTTCCATTGGTGTTTCCATTTGCACGTGCTTTCCTGAACGCCGCGGGAGATGACTAGTCGGACCTCATCCAAAAATCCTTTAAGGACAACAGGAATATCAAATGGATGGGCTTAGCGCCTCACGCGGATTGGCTGGCTGTTAGTCGACCCGTCCTCAGCCACGGAACCGTCAACGCCGGGATGCTGTTGTAACGTATCGCCGTGTTTAA",
"GTATCGTTCTGAGTTATAGTGGAGATCAAATTGGTCGGCCTGCCGCCTATCTGGTTGGTCACGAACGAGGACCATTTTAATATATAAGACGTGCGACTCACCCCGGAATTAATATTACGGTGACACGCGGAGCCGAATGGACTCCAATCGGTTCACCTGGAGGTCAAGGTGCCCTGTACAGCTCCGCGTTTGATTCCGTGCTTTCTGACCT",
"TATTGATTACCTAGACAGGAACTGAATGCAAGGGTAGCTTCTTGTAGCTCGCGAGGGTCCCTCCTGGCGAGCTTGTGGTCATTAAGCTTAAGCGCGTGAATTAATGTCCACGCTCCTTGGAATATAATAGAATTGTGCTAACGGGGAGTTGCCACCGTAGCTCGCGCATTCTGTAGTGCGATGCGGGCAAGGTCTGCACCAAACCGTCAGG",
"GCCCTCTCTTGGCTGCCGCCTCGCCCTTCGGATTCCTTGTTATGGTACCGGCTAGAATAACATACTTCAAAGTTTTGGCCTAAGGGGAAGTGGCTGTGCGTCGTCCATACGAGAACACCGTTCGACCATTCGGGTGACTTCGAGTAAACGATGCCTCCTCGCGAGGGTTGTGATCAGGCAGACACGTAGCGCGGATTGGAACACATGAGGA",
"GTTGTTTTGAATATCGTCTGCGGAGAACTCTATCTGATTACGCTGTATCATCAAACCTAGACTCCCTACGGGAAAAGAGTCGGGATACAGCACTCCGTTAACACATCGATTGGAATTGCCGGGAGAACCTGTTTCCGTCAGGGTGGTTGGGCAAAGATATACCGCGAAGATGCTGCATTACGCTGGATAAATGCGGCTTCGACCACGCATC",
"GTATCTAGCGCATTGTCGGATCTCAGGGAACATACATCGAGATATCAGGACTTCCCGATAGTGTATATTCCTATCGGCTGTCCCACTAGTCTGCCACCGGATTGGAATTACCGTCTCCCCAACACATCTTTCACACTTATATCCAAGCTTAATTCTGAAACCAACGCTAACCCTGGACTGGAACATCCTTCGGAACGTCCATTACATAAAC",
"TTGTACTATGATGGGAGGGGAGACAACCGACTGGTGCTTGAATGCGCGTGAAAGCCGGACTCTAAACGTTGGAACGCAGGACCGGCTTATTCTATCTTCCCGACATACCACGCTTCTTGGAATTATCCAGTCGCGAGCGGTCGGCAATGACTTGACGTTTACTCTGCGGCATACTGCCGGGCTCAGGACTCAGGTATACTACAGTACCCCC",
"GAGCTTCTCCTGATTTCCTCTTCACGCGGATTGAGGTAAAGCCCAGCGGGCTTCGCACTTGCCAGAGCGCAGCAGATACCATCGTCGTGGACGTTTCGGTCAGATACACTATATGTTCCGGCAAGCTAACACAGAAACCCAAAGCGACTCCACCTTGTGCGTCATTACACTACTAATAGCCTGCATCAACGTCTGCCTAGCCCGGCGACCT",
"GCTATCATGCGTAGCTTAATGCTCTCGGGTCGGGTCTGGATAGCGAGAAAACGCGGATTGGACGGGCCTCGTTATGCCGTACCCCCGTGACGTCTCTGAGTTTAACAATGAGTACCGGTCATCACCACCGGGTCACCCTTGCGGCCAACAAACTCCGTACTTTAGAACTCTAAAGTGGGATTTAAAAAACACGGTATGGTGTCAGTACAAC")



indices = sapply(test,convert2indices)

superN = 150
supermax = Inf
superset = NA
for( sup in seq(superN))
{
	if(sup %% 100 == 0) cat(sprintf("%d%%...",(sup/superN)*100))
	klist = unname(sapply(test,kdict,ksize=ksize, simplify=FALSE))
	motifs = t(sapply(sapply(klist,sample,1),tokenize))
	maxscore = getscore(motifs)
	thisscore = 0
	maxset = motifs
	tsize = length(test)

	while(TRUE){
		prof = getprofile(motifs)
		motifs = t(unname(apply(indices,2,bestmotif,profile=prof,k=ksize)))
		thisscore = getscore(motifs)
		if(thisscore < maxscore){
			maxscore = thisscore 
			maxset = motifs
		} else {
			break
		}
	}

	if( maxscore < supermax){
		print(maxscore)
		supermax = maxscore
		superset = maxset
	}
}
cat("finished!\n")
supermax
cat(sprintf("%s\n",apply(superset,1,paste,collapse="")))



